### ISSUE TITLE
Wyniki są dobre jednak nie przechodzi testów...

### ISSUE THREAD

**Issue by xKudlaty** [korona-science/homework-xKudlaty#1]
5
31
['China', 'Korea, South', 'Cruise Ship', 'Italy', 'Iran']
['China', 'Italy', 'Iran', 'Korea, South', 'France']
35
57

Wyniki z programu są prawidłowe dla wskazanych funkcji jednak nie przechodzi testów.

Czy jest możliwość udostępnienia większej ilości testów? (tak aby wskazać dowolny błędny przypadek)

Czy istnieje możliwość że testy przestały działać? (Są też inni którym nie przechodzą testy)

**Comment by xKudlaty** [comment]
pip install wheel

To powinna być odpowiedź na błąd podczas przygotowania testów.
Proponuję korzystać z pliku requirements.txt aby każdy mógł dodać bibliotekę oraz tworzyć testy automatyczne w pythonie (też jako plik) aby dało się sprawdzać poprawność lokalnie.

**Comment by kkarkowska** [comment]
date.strftime("%#m/%#d/%y")
**#d** działa na windowsie, **#-d** na linuxie

**Comment by RouNNdeL** [comment]
Testy działają poprawnie. Dzięki za sugestię z requierments.txt, myślałem o tym podczas tworzenia pierwszych testów, ale uznałem, że będą na tyle proste, że po za bibliotekami omawianymi na kursie nie będzie potrzeby instalacji dodatkowych. W tym momencie jak wszyscy mają już stworzone repozytoria trudno będzie im przekazać informację o konieczności utworzenia pliku, aczkolwiek postaramy się coś wymiślić. `wheel` dodam już w testach do kolejnej pracy domowej.

**Comment by xKudlaty** [comment]
Wszystko działa :) 
Dziękuję za pomoc
